# Azure Developer CLI configuration for StoryCircuit

name: storycircuit
metadata:
  template: storycircuit-social-media-agent@1.0.0

services:
  web:
    project: .
    language: python
    host: containerapp
    
infra:
  provider: bicep
  path: infra

pipeline:
  provider: github
